import dreem
import pickle
from rna_library.core import safe_rm, safe_mkdir


def process_histos(mut_hist_file: str, output_directory: str, remove_html: bool = True) -> None:
    """
    Processes a mutational histogram file generated by dreem. 
    
    :param: str mut_hist_file: path to the mutational histogram file
    :param: str output_directory: the output directory for the analysis files
    :param: bool remove_html: flag to remove .html files generated by DREEM, defaults to True 
    """
    pop_dir = f"{output_directory}/populations"
    class Params:
        class Dir:
            bitvector = pop_dir 
        dirs = Dir()

    data = pickle.load(open(mut_hist_file, "rb"))

    for histo in data.values():
        dreem.bit_vector.plot_population_avg(histo, Params())
    
    if remove_html:
        
        to_remove = list(glob(f"{pop_dir}/*html"))
        _ = list(map(safe_rm, to_remove))
